<!DOCTYPE html>

<?php 
if(isset($_GET['page'])){$page = $_GET['page'];} else {$page = 1;}
include("inc/blogdata.php");
$full = $_GET['full'];
$grade = $_GET['grade'];
?>

<title>Mobeta Blog</title>
      <meta name="description" content="Last news in Halifax Bouldering. Development, Sends, Exploration, New Boulders, Boulder Problems, Climbs.">
    </head>

<?php $pageTitle = "Mobeta";

include("inc/header.php");
?>



    <!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:250px">

    <!-- Site Header -->
    <div class="w3-display-container w3-container bgimg backgroundimage">    
    </div>

    <div id="content">

<?php

    // STEP 1 - creates an variable containing an array of IDs generated by the array_category function. Specify the input to pass to the search function 

$test = array_category($blogpost);

// STEP 2 - Search function - outputs an array of IDs based on parameters of a foreach loop, and specified input value $grade

function array_category($blogpost){
$output = array();
foreach ($blogpost as $id => $item){
              $sort = $item["date"];  
          $output[$id] = $sort;

        }
    
arsort($output);
return array_keys($output);
    }

// STEP 4 - function takes IDs and returns corresponding values from data.php 

function get_grade($full,$grade,$id,$item,$i){
    $hardgrade = ["V13","V12","V11","V10","V9","V8","V7","V6","V5","V4","V3","V2","V1"];
    $classicgrade = ["V15","V14","V13","V11","V10","V9","V8","V7","V5/6","V4","V3","V2","V1"];
    if($full == "y"){$fulllink = "&full=y";} else {$fulllink = "&full=n";} 
    if($grade == "h"){$gradelink3 = "&grade=h";} else {$gradelink3 = "&grade=TMI";} 
    if($grade == "TMI" or $grade == null){$blogtitle = $item['title'];} 
    if($grade == "h"){$blogtitle = $item['title'];} else {$blogtitle = str_replace($hardgrade,$classicgrade,$item['title']);}
    if($grade == "h"){$blogsummary = $item['summary'];;} else {$blogsummary = str_replace($hardgrade,$classicgrade,$item['summary']);}     
    $blogdate = $item['dateverbose'];
    $image1 = "/img/blo/".$item['date']."_1_600.jpg";
    $image1srcset = "/img/blo/".$item['date']."_1";
    $bloglink = "/blogpost.php?blog=".$item['date'];
    if (is_int($i/4)){$linebreak = "</div><div class='w3-light-grey w3-row-padding w3-center' id='food' style='margin-top:0px;''>";}

    $output =  
    "<div class='w3-quarter w3-margin-bottom'><a href='".$bloglink.$fulllink.$gradelink3."'><img src='".$image1."' alt='Weapons' style='width:100%' class='w3-hover-opacity sizes='(max-width:600px) 86vw, 38vw' srcset='".$image1srcset."_400.jpg 400w,".$image1srcset."_600.jpg 600w,".$image1srcset."_700.jpg 700w,".$image1srcset."_800.jpg 800w,".$image1srcset."_1000.jpg 1000w,".$image1srcset."_1100.jpg 1100w,".$image1srcset."_1600.jpg 1600w'></a><div class='w3-container w3-white w3-card-4'><h4>".$blogtitle."</h4><h6><span class='w3-opacity'>".$blogdate."</span></h6><p>".$blogsummary."</p></div></div>".$linebreak;
    return $output;
}



?>

  <!-- Blog post photo grid -->
  <div class="w3-light-grey w3-row-padding w3-padding-16 w3-center">
  <h5 class="w3-center w3-light-grey"><span class="w3-tag w3-wide">BLOG</span></h5>
</div>

<!-- First Row -->

  <div class="w3-light-grey w3-row-padding w3-center" id="food" style="margin-top:0px;">
    

<?php
    // STEP 4 code the calls the results of the sorted and formatted search array and inserts results into the page 
    $itemsperpage = 16;
    $pagestotal = ceil(count($test)/$itemsperpage);
    $arrayslice = array_slice($test,(0+($itemsperpage*($page -1))),$itemsperpage);
    $i = 1;
    foreach ($arrayslice as $id){
        echo get_grade($full,$grade,$id,$blogpost[$id],$i);
        $i +=1;
        }

       

        function addOrUpdateUrlParam($name, $value) // function to create links adding new html parameters while keeping the old ones
        {
            $params = $_GET;
            unset($params[$name]);
            $params[$name] = $value;
            return basename($_SERVER['PHP_SELF']).'?'.http_build_query($params);
        }
        
        // code to create pagination 
        
        $urlnext = addOrUpdateUrlParam("page", $page+1);
        $urlprevious = addOrUpdateUrlParam("page", $page-1);
        

?>        



    </div>

    <div class="w3-center">
 <?php if ($page > 1){echo "<a href='".$urlprevious."'>";} ?><button class="w3-button w3-large <?php if ($page > 1){echo "w3-black";} else {echo "w3-lightgrey";} ?>">&#8249;</button><?php if ($page > 1){echo "</a>";} ?>
 <?php if ($page < $pagestotal){echo "<a href='".$urlnext."'>";} ?><button class="w3-button w3-large <?php if ($page < $pagestotal){echo "w3-black";} else {echo "w3-lightgrey";} ?>">&#8250;</button><?php if ($page < $pagestotal){echo "</a>";} ?>
</div>

<?php include("inc/footer.php");?>

</body>
</html>
