<!DOCTYPE html>

<head>
  
      <title>Mobeta bouldering guidebook for Halifax Nova Scotia</title>
      <meta name="description" content="Mobeta is an online guidebook aiming to provide photos, video, and GPS for all Nova Scotia boulder problems on your mobile device. Halifax, climbing, bouldering, guidebook, Nova Scotia.">
    
    </head>

<?php 
// debug code
// error_reporting(E_ALL);
// ini_set('display_errors', 1);


$pageTitle = "Mobeta";
$grade = "h";
$full = $_GET['full'];
// include("inc/header.php");
include("inc/data.php");
$areas = $_GET['all'];
echo '<pre>';
print_r($problem);
echo '</pre>';
exit;
if(isset($_GET['page'])){$page = $_GET['page'];} else {$page = 1;}
include("inc/blogdata.php");


?>






    <!-- !PAGE CONTENT! -->
<div class="w3-main" style="margin-left:250px">

    <!-- Site Header -->
    <div class="w3-display-container w3-container bgimg backgroundimage">    
    </div>
    <?php

// STEP 1 - creates an variable containing an array of IDs generated by the array_category function. Specify the input to pass to the search function 

$test = array_category($blogpost);

// STEP 2 - Search function - outputs an array of IDs based on parameters of a foreach loop, and specified input value $grade

function array_category($blogpost){
$output = array();
foreach ($blogpost as $id => $item){
          $sort = $item["date"];  
      $output[$id] = $sort;

    }

arsort($output);
return array_keys($output);
}

// STEP 4 - function takes IDs and returns corresponding values from data.php 

function get_grade($full,$grade,$id,$item){
  $hardgrade = ["V13","V12","V11","V10","V9","V8","V7","V6","V5","V4","V3","V2","V1"];
  $classicgrade = ["V15","V14","V13","V11","V10","V9","V8","V7","V5/6","V4","V3","V2","V1"];
if($full == "y"){$fulllink2 = "&full=y";} else {$fulllink2 = "&full=n";} 
if($grade == "h"){$gradelink3 = "&grade=h";} else {$gradelink3 = "&grade=TMI";} 
if($grade == "h"){$blogtitle = $item['title'];} else {$blogtitle = str_replace($hardgrade,$classicgrade,$item['title']);}
if($grade == "h"){$blogsummary = $item['summary'];;} else {$blogsummary = str_replace($hardgrade,$classicgrade,$item['summary']);} 

$blogdate = $item['dateverbose'];

$image1 = "/img/blo/".$item['date']."_1_600.jpg";
$image1srcset = "/img/blo/".$item['date']."_1";
$bloglink = "/blogpost.php?blog=".$item['date'];

$output =  
"<div class='w3-quarter w3-margin-bottom'><a href='".$bloglink.$fulllink2.$gradelink3."'><img src='".$image1."' alt='Weapons' style='width:100%' class='w3-hover-opacity' sizes='(max-width:600px) 90vw, 20vw' srcset='".$image1srcset."_400.jpg 400w,".$image1srcset."_600.jpg 600w,".$image1srcset."_700.jpg 700w,".$image1srcset."_800.jpg 800w,".$image1srcset."_1000.jpg 1000w,".$image1srcset."_1100.jpg 1100w,".$image1srcset."_1600.jpg 1600w'></a><div class='w3-container w3-white w3-card-4'><h4>".$blogtitle."</h4><h6><span class='w3-opacity'>".$blogdate."</span></h6><p>".$blogsummary."</p></div></div>";
return $output;
}


?>


<!-- Blog post photo grid -->
<div class="w3-light-grey w3-row-padding w3-padding-16 w3-center">
<h5 class="w3-center w3-light-grey"><span class="w3-tag w3-wide">LATEST UPDATES</span></h5>
</div>

<!-- First Row -->

<div class="w3-light-grey w3-row-padding w3-center" id="food" style="margin-top:0px;">


<?php
// STEP 4 code the calls the results of the sorted and formatted search array and inserts results into the page 
$itemsperpage = 4;
$pagestotal = ceil(count($test)/$itemsperpage);
$arrayslice = array_slice($test,(0+($itemsperpage*($page -1))),$itemsperpage);
foreach ($arrayslice as $id){
    echo get_grade($full,$grade,$id,$blogpost[$id]);
    }

   
//
//   function addOrUpdateUrlParam($name, $value) // function to create links adding new html parameters while keeping the old ones
 //   {
//        $params = $_GET;
//        unset($params[$name]);
//        $params[$name] = $value;
//        return basename($_SERVER['PHP_SELF']).'?'.http_build_query($params);
//    }
    
    // code to create pagination 
    
//    $urlnext = addOrUpdateUrlParam("page", $page+1);
//    $urlprevious = addOrUpdateUrlParam("page", $page-1);
    

?>        



</div>
<!--
<div class="w3-center">
<?php // if ($page > 1){echo "<a href='".$urlprevious."'>";} ?><button class="w3-button w3-large <?php // if ($page > 1){echo "w3-black";} else {echo "w3-lightgrey";} ?>">&#8249;</button><?php if ($page > 1){echo "</a>";} ?>
<?php // if ($page < $pagestotal){echo "<a href='".$urlnext."'>";} ?><button class="w3-button w3-large <?php  // if ($page < $pagestotal){echo "w3-black";} else {echo "w3-lightgrey";} ?>">&#8250;</button><?php if ($page < $pagestotal){echo "</a>";} ?>
</div>
    -->  
    <!-- END FIRST ROW COPY AND PASTE -->

<!-- PSA 

<div id="PSA" class="w3-padding w3-hide w3-hide-large w3-hide-medium w3-top w3-show" style="margin-top:58px">

<title>PSA</title><div class='w3-content w3-center w3-large blog-text'><div><i class="fa fa-window-close w3-right w3-xxlarge" onclick="PSA()" aria-hidden="true"></i><div class='w3-container w3-white w3-card'><h2 class='w3-wide'>Whoo's Whimsical Home Reno: Fly-by Alert! 🦉🔨🎉</h2><p class='w3-opacity'><i>Apr 3rd 2023</i></p></div>
  
<img src='img/blo/PSA_1000.jpg' alt='none' width='100%' class='w3-center' sizes='(max-width:600px) 90vw, 768px' srcset='img/blo/PSA_600.jpg 600w, img/blo/PSA_1000.jpg 1000w, img/blo/PSA_1500.jpg 1500w'>

<div class='w3-container w3-white w3-card w3-display-container' style="height: 500px; overflow: scroll;"><p class='w3-left-align'><span style="color:">Hoot hoot! Owl's abode is gettin' a spruce! A lil' spring cleanin' turned up a wonky beam, oh dear! No frets, we're fixin' the roost lickety-split! April 7th, fly on by! 'Til then, flap elsewhere, or risk hoppin' over one wacky, un-cushioned landin'! 🦉✨🌸</p><div class=" w3-white w3-row-padding w3-padding-16 w3-center">
<a href="#"><h5 class="w3-center" onclick="PSA()"><span class="w3-tag w3-wide">CLOSE</span></h5></a><br><br><br><br><br><br>
</div>

</div>
</div></div></div>

-->

<!-- Bouldering Areas Container -->

  <div class="w3-light-grey w3-row-padding w3-margin-top w3-center " >
    <h5 class="w3-center w3-light-grey"><span class="w3-tag w3-wide">BOULDERING AREAS</span></h5>
  </div>

  <div class="w3-padding w3-xlarge w3-margin-bottom w3-center" style="color: red; font-weight: bold; background-color: rgb(241, 241, 241);;">Info-only site. No access guarantee. Land owner's discretion - consult local orgs. Climb at own risk; injury/death possible. Be safe, discreet, respectful. Leave no trace.
</div>

  

 

<?php include("areas.php");?>

<!-- Legend Container -->
<style>
.donut {
  width: 20px;
  height: 20px;
  background: radial-gradient(white 40%, transparent 41%),
    conic-gradient(#767677 0deg, #767677 70deg, #0623e0 110deg, #0623e0 250deg, #767677 280deg, #767677 360deg);;
  margin: 10px;
  display: inline-block;
  border-radius: 50%;
}

.donut::after {
  display: inline-block;
  content:'';
  position: flex;
  top: 0;
  left: 0;

  color: #fff;
  background-image: url("../img/ico/wind.png");
  background-size:100% 100%;
  width: 100%;
  height: 100%;

}
</style>

<div class='w3-container' id='where' style='padding-bottom:16px;'>
  <div class='w3-content' style='max-width:700px'>
    <h5 class='w3-center w3-padding'><span class='w3-tag w3-wide'>LEGEND</span></h5>
  </div>
</div>

  <div class='w3-container'>
    <div class='w3-center w3-content' style='max-width:700px'>
    <table class='w3-table w3-striped w3-white' >
      <tr>
        <td><i class='w3-text-yellow w3-large fas fa-solid fa-star'></i></td>
        <td>Above avg. Visit if nearby.</td>
     
      </tr>
      <tr>
        <td><i class='w3-text-red w3-large fas fa-solid fa-heart'></i></td>
        <td>Classic. Trip-worthy.</td>
      
      </tr>
      <tr>
        <td><img style="width: 19px; margin-top: -3px;" src='img/ico/bench.png' alt='star'></td>
        <td>Benchmark for quality, consistency, difficulty. Visit Nova Scotia.</td>
       
      </tr>
      <tr>
        <td><i class='w3-text-brown w3-large fas fa-solid fa-poo'></i></td>
        <td>Poor. Avoid, unless tick list short.</td>
       
      </tr>
      <tr>
        <td><i class='w3-text-green w3-large fas fa-solid fa-mountain'></i></td>
        <td>Tall line. Consider landing.</td>
      
      </tr>
      <tr>
        <td><i style="margin-left:2px;" class='w3-large fas fa-skull-crossbones'></i></td>
        <td>Risky line.</td>
      
      </tr>
      <tr>
        <td><img style="width: 19px; margin-top: -3px;" src='img/ico/sun.png' alt='star'></td>
        <td>Sun/shade hours. Plan session.</td>
     
      </tr>
      <tr>
        <td><span style="margin-left:0px;" class="donut"></span></td>
        <td>Wind exposure. Summer seek, winter avoid.</td>
       
      </tr>
      <tr>
        <td><i class='fa fa-cog w3-large'></i></td>
        <td>Toggle full/select topos & quality.</td>
       
      </tr>
    </table>
  </div>
</div>

<!-- End styling -->


    <?php include("inc/footer.php");?>




</body>
</html>
